{
 "title": "OSRT: Access",
 "description": "Metrics obtained from parsing Apache access logs for download.opensuse.org.",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "frequency", "label": "Aggregation Frequency", "query": "day, week, month, FQ, FY" },
   {
    "name": "product",
    "label": "Product",
    "query": "show tag values from image_month with key = \"product\""
   }
  ]
 },
 "panels": [
  {
   "title": "Explanation",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "These metrics were generated by parsing the Apache access logs of [download.opensuse.org](http://download.opensuse.org/).\n\n- A unique identifier (UUID) is included in logs when zypper includes it in the request. Multiple requests by the same UUID within the given aggregation frequency are counted as a single unique user.\n- UUID is a random label that is created during system installation.\n- The target product is determined by looking for specially formatted path elements representing build repositories for a particular product and the main repositories for that product.\n\n__The logs are entirely invalid, due to a config mistake, from _2017-12-07_ to _2018-03-08_ and the custom log format, which includes the UUID from zypper, was not present from _2018-03-08_ until _2018-05-29_ which is the cause of the large \"hole\" in the graphs.__\n\n__The logs for IPv4 access are missing from 2021-06-01 until 2021-09-05.__"
  },
  { "title": "Product", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Unique by Product (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_product",
     "groupBy": [
      { "params": [ "product" ], "type": "tag" }
     ],
     "measurement": "/^access_$frequency$/",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "product", "operator": "!=", "value": "-" }
     ]
    }
   ]
  },
  {
   "title": "Unique by Product",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_product",
     "groupBy": [
      { "params": [ "product" ], "type": "tag" }
     ],
     "measurement": "/^access_$frequency$/",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "product", "operator": "!=", "value": "-" }
     ]
    }
   ]
  },
  {
   "title": "Unique by Product (percentage)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_product",
     "groupBy": [
      { "params": [ "product" ], "type": "tag" }
     ],
     "measurement": "/^access_$frequency$/",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "product", "operator": "!=", "value": "-" }
     ]
    }
   ]
  },
  {
   "title": "Max Unique by Product",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "product" ], "type": "tag" }
     ],
     "measurement": "/^access_$frequency$/",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "product", "operator": "!=", "value": "-" }
     ]
    }
   ]
  },
  {
   "title": "Max Unique by Product",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_product",
     "groupBy": [
      { "params": [ "product" ], "type": "tag" }
     ],
     "measurement": "/^access_$frequency$/",
     "select": [
      [
       { "params": [ "unique" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "product", "operator": "!=", "value": "-" }
     ]
    }
   ]
  },
  {
   "title": "Total / Unique",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total vs Unique",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "measurement": "/^access_$frequency$/",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ],
        [
         { "params": [ "unique" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=", "value": "-" }
       ]
      }
     ]
    },
    {
     "title": "Average per Unique",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_product",
       "groupBy": [
        { "params": [ "product" ], "type": "tag" }
       ],
       "measurement": "/^access_$frequency$/",
       "select": [
        [
         { "params": [ "unqiue_average" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "!=", "value": "-" }
       ]
      }
     ]
    },
    {
     "title": "Max per Unique",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_product",
       "groupBy": [
        { "params": [ "product" ], "type": "tag" }
       ],
       "measurement": "/^access_$frequency$/",
       "select": [
        [
         { "params": [ "unqiue_max" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "!=", "value": "-" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests by IP Protocol",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_protocol",
       "groupBy": [
        { "params": [ "protocol" ], "type": "tag" }
       ],
       "measurement": "/^protocol_$frequency$/",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Unique Requests by IP Protocol",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_protocol",
       "groupBy": [
        { "params": [ "protocol" ], "type": "tag" }
       ],
       "measurement": "/^protocol_$frequency$/",
       "select": [
        [
         { "params": [ "unique" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Requests by IP Protocol (percentage)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_protocol",
       "groupBy": [
        { "params": [ "protocol" ], "type": "tag" }
       ],
       "measurement": "/^protocol_$frequency$/",
       "select": [
        [
         { "params": [ "total" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Unique Requests by IP Protocol (percentage)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_protocol",
       "groupBy": [
        { "params": [ "protocol" ], "type": "tag" }
       ],
       "measurement": "/^protocol_$frequency$/",
       "select": [
        [
         { "params": [ "unique" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Tool Feedback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Log Size",
     "type": "singlestat",
     "description": "The amount of Apache access log data for which these metrics represent.",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 47 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "measurement": "/^access_$frequency$/",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=", "value": "-" }
       ]
      }
     ]
    },
    {
     "title": "Invalid Log Entries",
     "type": "singlestat",
     "description": "The number of invalid entries in access log that were not able to be parsed and therefore excluded from metrics.",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 47 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "/^access_$frequency$/",
       "select": [
        [
         { "params": [ "total_invalid" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=", "value": "-" }
       ]
      }
     ]
    },
    {
     "title": "Raw Log Size",
     "type": "graph",
     "description": "The amount of Apache access log data for which these metrics represent.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_product",
       "groupBy": [
        { "params": [ "product" ], "type": "tag" }
       ],
       "measurement": "/^access_$frequency$/",
       "select": [
        [
         { "params": [ "bytes" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=", "value": "-" }
       ]
      }
     ]
    },
    {
     "title": "Invalid Log Entries",
     "type": "graph",
     "description": "The number of invalid entries in access log that were not able to be parsed and therefore excluded from metrics.\n\nFrom manual examination records determined to be invalid are indeed invalid, but obviously if the majority of access ends up being marked as invalid that may be a sign of issues.\n\nA DOS attack caused large amounts of invalid entries in 2014 and many others are exploit attacks containing things like sql injection as a user-agent.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "product" ], "type": "tag" }
       ],
       "measurement": "/^access_$frequency$/",
       "select": [
        [
         { "params": [ "total_invalid" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=", "value": "-" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Image Media - $product",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total by Image (stacked)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_key",
       "groupBy": [
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "/^image_$frequency$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=~", "value": "/^$product$/" }
       ]
      }
     ]
    },
    {
     "title": "Total by Image",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_key",
       "groupBy": [
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "/^image_$frequency$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=~", "value": "/^$product$/" }
       ]
      }
     ]
    },
    {
     "title": "Total by Image (percentage)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_key",
       "groupBy": [
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "/^image_$frequency$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=~", "value": "/^$product$/" }
       ]
      }
     ]
    },
    {
     "title": "Total by Image (percentage - zoomed)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_key",
       "groupBy": [
        { "params": [ "key" ], "type": "tag" }
       ],
       "measurement": "/^image_$frequency$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "product", "operator": "=~", "value": "/^$product$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}